export enum ButtonVariant {
  icon = "icon",
  primaryIcon = "primary-icon",
  primaryIconMono = "primary-icon-mono",
  primaryText = "primary-text",
  primaryFilled = "primary-filled",
  primaryOutlined = "primary-outlined",
  primaryTextWithIcon = "primary-text-with-icon",
  primaryFilledWithIcon = "primary-filled-with-icon",
  primaryOutlinedWithIcon = "primary-outlined-with-icon",
  secondaryIcon = "secondary-icon",
  secondaryText = "secondary-text",
  secondaryFilled = "secondary-filled",
  secondaryOutlined = "secondary-outlined",
  secondaryTextWithIcon = "secondary-text-with-icon",
  secondaryFilledWithIcon = "secondary-filled-with-icon",
  secondaryOutlinedWithIcon = "secondary-outlined-with-icon",
  dangerIcon = "danger-icon",
  dangerText = "danger-text",
  dangerFilled = "danger-filled",
  dangerOutlined = "danger-outlined",
  dangerTextWithIcon = "danger-text-with-icon",
  dangerFilledWithIcon = "danger-filled-with-icon",
  dangerOutlinedWithIcon = "danger-outlined-with-icon",
  textWithIcon = "text-with-icon",
}
